# This is a basic workflow to help you get started with Actions

name: CD
env:
  DESTINATION: 'Service'

on: [push, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  pre:
    runs-on: ubuntu-latest
    steps:
      - name: Show where is triggered from
        run: |
          echo d-lama-service ci/cd pipeline is triggered.
  # This workflow contains a single job called "build"
  cd:
    needs:
      - pre
    uses: d-lama/ops-d-lama-service/.github/workflows/d-lama-service-cd.yml@main
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
