# This is a basic workflow to help you get started with Actions

name: CI
env:
  DESTINATION: 'Service'

on: [push, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  call:
    runs-on: ubuntu-latest
    steps:
      - name: Show where is triggered from
        run: |
          echo $DESTINATION
          ls -la
          echo "DESTINATION=Service" >> $GITHUB_OUTPUT
          echo $GITHUB_OUTPUT
  # This workflow contains a single job called "build"
  checkout:
   uses: d-lama/ops-d-lama-service/.github/workflows/d-lama-service-ci.yml@main
